### PR TITLE
add jessie support. closes #17.

### LINKED ISSUE #17: Add support for Debian 9 (Jessie).

### PR DESCRIPTION
**Pull request by kirjatoukka**

### CODE REVIEW

**Comment by nickcharlton** [comment]
Does the change to `pressed.cfg` cause any side effects to `trusty` or `precise`?

**Comment by kirjatoukka** [comment]
It shouldn't, but I could be wrong. Going to run some builds now.

**Comment by kirjatoukka** [comment]
Also, I need to remove the `headless`.

**Comment by kirjatoukka** [comment]
All seem to build fine. However, I'm not certain if any or all will build with the default `ssh_wait_timeout`; I had to increase it on several of them.

**Comment by nickcharlton** [comment]
Merged.

**Pull request closed without merging**
